name: Run Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        pip install "sqlalchemy<2.0.0"  # Temporary fix for compatibility
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        pytest -v test_main.py
